apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd/test"
type: Opaque
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
  database_url: {{ .Values.secrets.database_url }}

