apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/data/argocd/test"
type: Opaque
stringData:
  username: {{ .Values.secrets.username }}
  password: {{ .Values.secrets.password }}
  database_url: {{ .Values.secrets.database_url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: default
data:
  app-name: {{ .Chart.Name }}
  app-version: {{ .Chart.AppVersion }}
